import React,{useMemo,useRef,useState}from'react';
import{Bot,Camera,CalendarDays,CheckCircle2,MapPin,MessageSquareText,Phone,Send,Sparkles,Upload,X,Building2,ChevronLeft}from'lucide-react';
import{BRAND}from'../data/mock';

const gold='#e8b94e';
const AIAssistant=()=>{
 const[open,setOpen]=useState(false),[mode,setMode]=useState('home'),[step,setStep]=useState(0),[input,setInput]=useState(''),[error,setError]=useState(''),[chat,setChat]=useState([]),[photos,setPhotos]=useState([]);
 const[answers,setAnswers]=useState({damage:'',wheels:'',zip:'',time:'',name:'',phone:'',vehicle:'',finish:''}); const fileRef=useRef(null);
 const questions=[['damage','What happened to your wheel?'],['wheels','How many wheels need repair?'],['vehicle','What vehicle do you have?'],['zip','What ZIP code or city is the vehicle in?'],['time','What day or time works best for you?'],['name','What is your name?'],['phone','What phone number should we use to contact you?']]; const done=step>=questions.length;
 const smallTalk=v=>{const s=v.toLowerCase().replace(/[?!.,]/g,'').trim();if(/^(hi|hello|hey|good morning|good afternoon|good evening|привет|здравствуйте)$/.test(s))return"Hi! 👋 Welcome to Rim Repair Pro. I'm doing great — how can I help with your wheels today?";if(/how are you|how r you|как дела|как вы/.test(s))return"I'm doing great, thank you! 😊 Tell me what happened to your wheel and I'll help.";if(/price|cost|how much|сколько|цена/.test(s))return"Pricing depends on the damage, wheel finish and number of wheels. I can collect everything now, then Sargis will personally confirm the final price.";if(/how.*repair|how.*work|как.*делаете|как.*ремонт/.test(s))return"We inspect and clean the wheel, prepare and smooth the damaged area, match the finish, refinish it and inspect the result — all at your location.";if(/crack|bent|трещ|гнут/.test(s))return"We specialize in cosmetic wheel repair such as curb rash, scratches and finish damage. Bent or cracked wheels require a different repair service.";return null};
 const validate=(k,v)=>{if(!v.trim())return'Please enter an answer.';if(k==='wheels'&&!/^[1-4]$/.test(v.trim()))return'Choose 1, 2, 3 or 4 wheels.';if(k==='phone'&&v.replace(/\D/g,'').length<10)return'Please enter a valid phone number.';return''};
 const submit=(forced)=>{if(done)return;const v=(forced??input).trim();if(!v)return;const reply=smallTalk(v);if(reply){setChat(c=>[...c,{u:v,a:reply}]);setInput('');return}const k=questions[step][0],msg=validate(k,v);if(msg){setError(msg);return}setAnswers(a=>({...a,[k]:v}));setInput('');setError('');setStep(s=>s+1)};
 const addPhotos=e=>{const f=Array.from(e.target.files||[]).filter(x=>x.type.startsWith('image/')).slice(0,4-photos.length);setPhotos(p=>[...p,...f.map(file=>({file,url:URL.createObjectURL(file)}))]);e.target.value=''};
 const lead=useMemo(()=>`NEW RIM REPAIR AI LEAD\n\nCustomer: ${answers.name}\nPhone: ${answers.phone}\nVehicle: ${answers.vehicle}\nDamage: ${answers.damage}\nWheels: ${answers.wheels}\nArea: ${answers.zip}\nPreferred time: ${answers.time}\nPhotos selected: ${photos.length}\n\nPlease contact me to confirm price and appointment.`,[answers,photos]);
 const resetMode=m=>{setMode(m);setError('');if(m==='quote')setStep(0)};
 const tile=(Icon,title,sub,m)=><button onClick={()=>resetMode(m)} className="group rounded-xl border border-white/10 bg-[#111416] p-4 text-left transition hover:border-[#e8b94e]/60 hover:bg-[#171a1d]"><Icon className="h-5 w-5 text-[#e8b94e]"/><div className="mt-3 text-sm font-black text-white">{title}</div><div className="mt-1 text-[11px] text-zinc-500">{sub}</div></button>;
 const Header=()=> <div className="flex items-center justify-between border-b border-white/10 px-4 py-4 md:px-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full border border-[#e8b94e]/50 bg-[#e8b94e]/10"><Bot className="h-6 w-6 text-[#e8b94e]"/></div><div><div className="text-base font-black text-[#e8b94e] md:text-xl">RIM REPAIR PRO</div><div className="text-sm font-bold text-white">AI CENTER</div></div></div><div className="flex gap-1">{mode!=='home'&&<button onClick={()=>setMode('home')} className="p-2 text-zinc-400 hover:text-white"><ChevronLeft/></button>}<button onClick={()=>setOpen(false)} className="p-2 text-zinc-400 hover:text-white"><X/></button></div></div>;
 return <><button onClick={()=>setOpen(true)} className="fixed bottom-[82px] right-4 z-40 flex items-center gap-2 rounded-full border border-[#f0c65c]/50 bg-[#e8b94e] px-5 py-3.5 text-xs font-black text-black shadow-[0_12px_40px_rgba(0,0,0,.5)] md:bottom-6 md:right-6"><Bot className="h-5 w-5"/>Rim Repair AI<span className="hidden sm:inline"> • Scan • Quote • Book</span></button>
 {open&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/70 md:items-center md:p-6" onClick={()=>setOpen(false)}><div onClick={e=>e.stopPropagation()} className="flex h-[92vh] w-full max-w-6xl flex-col overflow-hidden border border-[#e8b94e]/60 bg-[#090b0c] shadow-[0_25px_100px_rgba(0,0,0,.75)] md:h-[760px] md:max-h-[92vh] md:rounded-2xl"><Header/><div className="flex-1 overflow-y-auto p-4 md:p-6">\ {mode==='home'&&<><div className="mb-5"><div className="text-xl font-black text-white md:text-3xl">Your AI assistant for <span className="text-[#e8b94e]">wheel repair.</span></div><div className="mt-1 text-sm text-zinc-400">Scan your wheel, ask questions, request a quote, check your area or book service — all in one place.</div></div><div className="grid grid-cols-2 gap-2 md:grid-cols-6 md:gap-3">{tile(Camera,'Scan My Wheel','Photo analysis','scan')}{tile(MessageSquareText,'Ask AI','Chat support','chat')}{tile(Sparkles,'Get a Quote','Collect details','quote')}{tile(CalendarDays,'Book Service','Choose time','book')}{tile(MapPin,'Check My Area','ZIP / city','area')}{tile(Building2,'Dealer / B2B','Multiple vehicles','dealer')}</div><div className="mt-6 grid gap-4 md:grid-cols-2"><button onClick={()=>fileRef.current?.click()} className="min-h-[260px] rounded-2xl border-2 border-dashed border-white/15 bg-[#0f1214] p-8 text-center hover:border-[#e8b94e]/60"><Upload className="mx-auto h-10 w-10 text-[#e8b94e]"/><div className="mt-4 text-xl font-black text-white">Upload a photo of your wheel</div><div className="mt-2 text-sm text-zinc-500">Choose up to 4 clear photos from your phone.</div><div className="mx-auto mt-5 w-fit rounded-lg bg-[#e8b94e] px-6 py-3 text-sm font-black text-black">Upload Photo</div></button><div className="rounded-2xl border border-white/10 bg-[#0f1214] p-6"><div className="text-xs font-black uppercase tracking-[.18em] text-[#e8b94e]">AI Center</div><div className="mt-3 text-2xl font-black text-white">From photo to appointment.</div><div className="mt-4 space-y-3 text-sm text-zinc-400"><div>✓ Identify likely cosmetic damage</div><div>✓ Collect vehicle, wheel count and location</div><div>✓ Answer common repair questions</div><div>✓ Build a repair request summary</div><div>✓ Send everything to Rim Repair Pro</div></div><div className="mt-6 text-xs leading-5 text-zinc-600">AI results are preliminary. Sargis personally confirms repairability, final price and appointment.</div></div></div></>}
 {mode==='scan'&&<div className="mx-auto max-w-3xl"><h3 className="text-2xl font-black text-white">Scan My Wheel</h3><p className="mt-2 text-sm text-zinc-400">Upload clear photos. This first version collects the images for review; final damage assessment is confirmed by Rim Repair Pro.</p><button onClick={()=>fileRef.current?.click()} className="mt-6 w-full rounded-2xl border-2 border-dashed border-white/15 bg-[#101315] p-10"><Camera className="mx-auto h-12 w-12 text-[#e8b94e]"/><div className="mt-3 font-black text-white">Upload Wheel Photos</div></button>{photos.length>0&&<><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{photos.map((p,i)=><img key={p.url} src={p.url} alt={`Wheel ${i+1}`} className="aspect-square w-full rounded-xl object-cover"/>)}</div><button onClick={()=>setMode('quote')} className="mt-5 w-full rounded-xl bg-[#e8b94e] py-4 font-black text-black">Continue to Get Quote</button></>}</div>}
 {mode==='chat'&&<div className="mx-auto flex min-h-[520px] max-w-3xl flex-col"><div className="flex-1 space-y-3"><div className="max-w-[85%] rounded-2xl bg-[#202326] p-4 text-zinc-100">Hi 👋 I’m the Rim Repair Pro assistant. Ask me about cosmetic wheel repair, mobile service, pricing, or how the process works.</div>{chat.map((m,i)=><React.Fragment key={i}><div className="ml-auto max-w-[80%] rounded-2xl bg-[#e8b94e] p-3 font-bold text-black">{m.u}</div><div className="max-w-[85%] rounded-2xl bg-[#202326] p-4 text-zinc-100">{m.a}</div></React.Fragment>)}</div><div className="mt-4 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){const r=smallTalk(input)||"I can help with cosmetic curb rash, scratches, mobile service and quote requests. For anything specific, Sargis will personally review it.";setChat(c=>[...c,{u:input,a:r}]);setInput('')}}} placeholder="Type a message..." className="flex-1 rounded-xl border border-white/15 bg-[#141719] px-4 text-white outline-none focus:border-[#e8b94e]"/><button onClick={()=>{if(!input.trim())return;const r=smallTalk(input)||"I can help with cosmetic curb rash, scratches, mobile service and quote requests. For anything specific, Sargis will personally review it.";setChat(c=>[...c,{u:input,a:r}]);setInput('')}} className="grid h-12 w-12 place-items-center rounded-full bg-[#e8b94e] text-black"><Send/></button></div></div>}
 {mode==='quote'&&<div className="mx-auto max-w-3xl"><h3 className="text-2xl font-black text-white">Get a Quote</h3><div className="mt-5 space-y-3">{questions.slice(0,step).map(([k,q])=><div key={k}><div className="text-xs text-zinc-500">{q}</div><div className="mt-1 rounded-xl bg-[#171a1c] p-3 font-bold text-white">{answers[k]}</div></div>)}{!done&&<><div className="rounded-xl bg-[#202326] p-4 text-white">{questions[step][1]}</div><div className="flex gap-2"><input value={input} onChange={e=>{setInput(e.target.value);setError('')}} onKeyDown={e=>e.key==='Enter'&&submit()} className="flex-1 rounded-xl border border-white/15 bg-[#141719] px-4 py-3 text-white outline-none focus:border-[#e8b94e]" placeholder="Type your answer..."/><button onClick={()=>submit()} className="rounded-xl bg-[#e8b94e] px-5 text-black"><Send/></button></div>{error&&<div className="text-xs font-bold text-red-400">{error}</div>}{questions[step][0]==='wheels'&&<div className="flex gap-2">{['1','2','3','4'].map(x=><button key={x} onClick={()=>submit(x)} className="flex-1 rounded-lg border border-[#e8b94e]/40 py-2 font-bold text-[#e8b94e]">{x}</button>)}</div>}</>}{done&&<div className="rounded-2xl border border-[#e8b94e]/30 bg-[#101315] p-5"><div className="text-xl font-black text-[#e8b94e]">YOUR REPAIR SUMMARY</div><div className="mt-4 grid gap-2 text-sm text-zinc-300"><div>Vehicle: <b className="text-white">{answers.vehicle}</b></div><div>Wheels: <b className="text-white">{answers.wheels}</b></div><div>Damage: <b className="text-white">{answers.damage}</b></div><div>Location: <b className="text-white">{answers.zip}</b></div><div>Preferred: <b className="text-white">{answers.time}</b></div><div>Photos: <b className="text-white">{photos.length}</b></div></div><button onClick={()=>window.location.href=`sms:${BRAND.phoneTel}?body=${encodeURIComponent(lead)}`} className="mt-5 w-full rounded-xl bg-[#e8b94e] py-4 font-black text-black">Send to Rim Repair Pro</button></div>}</div></div>}
 {mode==='book'&&<div className="mx-auto max-w-2xl"><h3 className="text-2xl font-black text-white">Book Service</h3><p className="mt-2 text-zinc-400">Choose your preferred window. Sargis will confirm availability by text.</p><div className="mt-6 grid grid-cols-2 gap-3">{['8–10 AM','10 AM–12 PM','12–2 PM','2–4 PM','4–6 PM'].map(t=><button key={t} onClick={()=>{setAnswers(a=>({...a,time:t}));setMode('quote')}} className="rounded-xl border border-white/15 bg-[#121517] p-4 font-bold text-white hover:border-[#e8b94e] hover:text-[#e8b94e]">{t}</button>)}</div></div>}
 {mode==='area'&&<div className="mx-auto max-w-2xl"><h3 className="text-2xl font-black text-white">Check My Area</h3><p className="mt-2 text-zinc-400">Enter your ZIP code or city. Rim Repair Pro provides mobile service across many Los Angeles areas.</p><div className="mt-6 flex gap-2"><input value={answers.zip} onChange={e=>setAnswers(a=>({...a,zip:e.target.value}))} placeholder="ZIP code or city" className="flex-1 rounded-xl border border-white/15 bg-[#141719] px-4 text-white outline-none focus:border-[#e8b94e]"/><button onClick={()=>setMode('quote')} className="rounded-xl bg-[#e8b94e] px-5 font-black text-black">Continue</button></div></div>}
 {mode==='dealer'&&<div className="mx-auto max-w-2xl"><Building2 className="h-10 w-10 text-[#e8b94e]"/><h3 className="mt-3 text-2xl font-black text-white">Dealer / Body Shop / B2B</h3><p className="mt-3 leading-7 text-zinc-400">Need recurring mobile wheel repair or multiple vehicles? Send your business request directly to Rim Repair Pro for dealer pricing and scheduling.</p><a href="/dealers" className="mt-6 inline-flex rounded-xl bg-[#e8b94e] px-6 py-4 font-black text-black">Open Business Partners</a></div>}
 </div><input ref={fileRef} type="file" accept="image/*" multiple className="hidden" onChange={addPhotos}/><div className="border-t border-white/10 px-4 py-3 text-center text-[10px] text-zinc-600">Rim Repair Pro AI Center • Preliminary assistance only • Final repair approval, pricing and scheduling are confirmed by Rim Repair Pro</div></div></div>}</>};
export default AIAssistant;
