import React,{useRef,useState}from'react';
import{Bot,Camera,CalendarDays,Building2,MapPin,MessageSquareText,Send,Sparkles,Upload,X}from'lucide-react';
import{BRAND}from'../data/mock';

export default function AIAssistant(){
 const[open,setOpen]=useState(false),[mode,setMode]=useState('home'),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState('');
 const[messages,setMessages]=useState([{role:'assistant',content:"Hi 👋 I’m the Rim Repair Pro AI assistant. Ask me anything about cosmetic wheel repair, pricing, mobile service, or upload a wheel photo for a preliminary visual assessment."}]);
 const fileRef=useRef(null);
 const callAI=async(next,image)=>{setError('');setBusy(true);try{const r=await fetch('/api/ai-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next,image})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI unavailable');setMessages([...next,{role:'assistant',content:d.reply}]);return true}catch(e){console.error(e);setError('AI is temporarily unavailable. You can call or text us at (747) 717-0060.');return false}finally{setBusy(false)}};
 const send=async()=>{const value=text.trim();if(!value||busy)return;const next=[...messages,{role:'user',content:value}];setMessages(next);setText('');await callAI(next)};
 const resizeImage=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.82))};img.src=reader.result};reader.readAsDataURL(file)});
 const upload=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!file.type.startsWith('image/')){setError('Please choose a photo of the wheel.');return}setMode('chat');setError('');try{const data=await resizeImage(file);setPreview(data);const next=[...messages,{role:'user',content:'I uploaded a wheel photo. Please analyze the visible cosmetic damage, apparent finish/color, and what information you need from me next.'}];setMessages(next);await callAI(next,data)}catch(err){console.error(err);setError('We could not read that photo. Please try another image.')}};
 const cards=[[Camera,'Scan My Wheel','AI photo assessment','scan'],[MessageSquareText,'Ask AI','Real AI chat','chat'],[Sparkles,'Get a Quote','Send repair details','quote'],[CalendarDays,'Book Service','Choose preferred time','book'],[MapPin,'Check My Area','Mobile service area','area'],[Building2,'Dealer / B2B','Business partners','dealer']];
 const go=m=>{if(m==='dealer'){window.location.href='/dealers';return}if(m==='quote'||m==='book'||m==='area'){window.location.href='/#contact';setOpen(false);return}setMode(m)};
 return <><button onClick={()=>setOpen(true)} className="fixed bottom-[82px] right-4 z-40 flex items-center gap-2 rounded-full border border-[#e8b94e]/50 bg-[#e8b94e] px-5 py-3.5 text-xs font-black text-black shadow-2xl md:bottom-6 md:right-6"><Bot className="h-5 w-5"/>Rim Repair AI<span className="hidden sm:inline"> • Scan • Quote • Book</span></button>
 {open&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/70 md:items-center md:p-6" onClick={()=>setOpen(false)}><div onClick={e=>e.stopPropagation()} className="flex h-[92vh] w-full max-w-6xl flex-col overflow-hidden border border-[#e8b94e]/60 bg-[#090b0c] shadow-2xl md:h-[760px] md:rounded-2xl">
 <header className="flex items-center justify-between border-b border-white/10 p-4 md:px-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full border border-[#e8b94e]/50 bg-[#e8b94e]/10"><Bot className="text-[#e8b94e]"/></div><div><div className="font-black text-[#e8b94e]">RIM REPAIR PRO</div><div className="text-sm font-bold text-white">AI CENTER</div></div></div><div className="flex gap-2">{mode!=='home'&&<button onClick={()=>setMode('home')} className="rounded-lg border border-white/10 px-3 text-sm text-zinc-300">Back</button>}<button onClick={()=>setOpen(false)} className="p-2 text-zinc-400"><X/></button></div></header>
 <main className="flex-1 overflow-y-auto p-4 md:p-6">
 {mode==='home'&&<><h2 className="text-2xl font-black text-white md:text-3xl">Your AI assistant for <span className="text-[#e8b94e]">wheel repair.</span></h2><p className="mt-2 text-sm text-zinc-400">Ask questions, upload a wheel photo, request a quote, check your area or book service.</p><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-6">{cards.map(([I,t,s,m])=><button key={m} onClick={()=>go(m)} className="rounded-xl border border-white/10 bg-[#111416] p-4 text-left hover:border-[#e8b94e]/60"><I className="h-5 w-5 text-[#e8b94e]"/><div className="mt-3 text-sm font-black text-white">{t}</div><div className="mt-1 text-[11px] text-zinc-500">{s}</div></button>)}</div><div className="mt-6 grid gap-4 md:grid-cols-2"><button onClick={()=>fileRef.current?.click()} className="min-h-[260px] rounded-2xl border-2 border-dashed border-white/15 bg-[#0f1214] p-8 text-center hover:border-[#e8b94e]/60"><Upload className="mx-auto h-10 w-10 text-[#e8b94e]"/><div className="mt-4 text-xl font-black text-white">Upload a photo of your wheel</div><div className="mt-2 text-sm text-zinc-500">AI will inspect visible cosmetic damage and wheel finish.</div></button><button onClick={()=>setMode('chat')} className="rounded-2xl border border-[#e8b94e]/25 bg-[#0f1214] p-8 text-left"><Sparkles className="h-8 w-8 text-[#e8b94e]"/><div className="mt-4 text-2xl font-black text-white">Talk to Rim Repair AI</div><div className="mt-2 text-sm leading-6 text-zinc-400">Natural AI conversation that remembers the current chat and helps prepare your repair request.</div></button></div></>}
 {mode==='chat'&&<div className="mx-auto flex min-h-[560px] max-w-3xl flex-col"><div className="flex-1 space-y-3">{messages.map((m,i)=><div key={i} className={(m.role==='user'?'ml-auto bg-[#e8b94e] text-black font-semibold':'mr-auto bg-[#202326] text-zinc-100')+' max-w-[86%] whitespace-pre-wrap rounded-2xl p-4'}>{m.content}</div>)}{preview&&<div className="ml-auto max-w-[70%]"><img src={preview} alt="Uploaded wheel" className="max-h-64 w-full rounded-2xl border border-[#e8b94e]/30 object-cover"/></div>}{busy&&<div className="mr-auto rounded-2xl bg-[#202326] p-4 text-zinc-400">Analyzing…</div>}{error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}</div><div className="sticky bottom-0 mt-4 bg-[#090b0c] pt-3"><div className="mb-2 flex gap-2"><button disabled={busy} onClick={()=>fileRef.current?.click()} className="flex items-center gap-2 rounded-lg border border-white/15 px-3 py-2 text-xs font-bold text-zinc-300 disabled:opacity-50"><Camera className="h-4 w-4 text-[#e8b94e]"/>Add Photo</button></div><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask anything about your wheel..." className="min-w-0 flex-1 rounded-xl border border-white/15 bg-[#141719] px-4 py-3 text-white outline-none focus:border-[#e8b94e]"/><button disabled={busy} onClick={send} className="grid h-12 w-12 place-items-center rounded-full bg-[#e8b94e] text-black disabled:opacity-50"><Send className="h-5 w-5"/></button></div></div></div>}
 {mode==='scan'&&<div className="mx-auto max-w-2xl text-center"><Camera className="mx-auto h-12 w-12 text-[#e8b94e]"/><h3 className="mt-4 text-2xl font-black text-white">Scan My Wheel with AI</h3><p className="mt-2 text-sm leading-6 text-zinc-400">Upload a clear photo showing the full wheel and damaged area. AI will describe visible cosmetic damage and apparent finish. The assessment is preliminary; Sargis confirms repairability and final price.</p><button onClick={()=>fileRef.current?.click()} className="mt-6 rounded-xl bg-[#e8b94e] px-8 py-4 font-black text-black">Choose Wheel Photo</button></div>}
 </main><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={upload}/><footer className="border-t border-white/10 px-4 py-3 text-center text-[10px] text-zinc-600">AI assistance is preliminary • Final repair approval, pricing and scheduling are confirmed by Rim Repair Pro • {BRAND.phone}</footer></div></div>}</>;
}
