import React,{useState}from'react';
import{ArrowLeft,Bot,Loader2,Phone,Send}from'lucide-react';
import{BRAND}from'../data/mock';

export default function AIChat(){
 const[messages,setMessages]=useState([{role:'assistant',content:"Hi 👋 I’m the Rim Repair Pro AI assistant. Ask me anything about your wheel damage, our mobile service, pricing process, or how to get a quote."}]);
 const[input,setInput]=useState(''); const[loading,setLoading]=useState(false); const[error,setError]=useState('');
 const send=async()=>{const text=input.trim();if(!text||loading)return;const next=[...messages,{role:'user',content:text}];setMessages(next);setInput('');setError('');setLoading(true);try{const r=await fetch('/api/ai-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI unavailable');setMessages(m=>[...m,{role:'assistant',content:d.reply}]);}catch(e){setError(e.message||'AI is temporarily unavailable.');}finally{setLoading(false)}};
 return <div className="min-h-screen bg-[#080a0b] text-white"><header className="sticky top-0 z-10 border-b border-white/10 bg-[#080a0b]/95 px-4 py-4 backdrop-blur"><div className="mx-auto flex max-w-3xl items-center justify-between"><a href="/" className="flex items-center gap-2 text-sm font-bold text-zinc-400 hover:text-white"><ArrowLeft className="h-5 w-5"/>Back</a><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full border border-[#e8b94e]/50 bg-[#e8b94e]/10"><Bot className="h-5 w-5 text-[#e8b94e]"/></div><div className="text-left"><div className="font-black text-[#e8b94e]">RIM REPAIR PRO</div><div className="text-xs font-bold">REAL AI ASSISTANT</div></div></div><a href={`tel:${BRAND.phoneTel}`} className="grid h-10 w-10 place-items-center rounded-full border border-[#e8b94e]/40 text-[#e8b94e]"><Phone className="h-5 w-5"/></a></div></header><main className="mx-auto flex min-h-[calc(100vh-74px)] max-w-3xl flex-col px-4"><div className="flex-1 space-y-4 py-6">{messages.map((m,i)=><div key={i} className={m.role==='user'?'ml-auto max-w-[85%] rounded-2xl rounded-tr-sm bg-[#e8b94e] px-4 py-3 font-semibold text-black':'max-w-[88%] rounded-2xl rounded-tl-sm bg-[#202326] px-4 py-3 leading-6 text-zinc-100'}>{m.content}</div>)}{loading&&<div className="flex w-fit items-center gap-2 rounded-2xl bg-[#202326] px-4 py-3 text-zinc-400"><Loader2 className="h-4 w-4 animate-spin"/>Thinking…</div>}{error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}</div><div className="sticky bottom-0 bg-[#080a0b] pb-5 pt-3"><div className="flex gap-2 rounded-2xl border border-white/15 bg-[#121517] p-2 focus-within:border-[#e8b94e]/70"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask anything about your wheel…" className="min-w-0 flex-1 bg-transparent px-3 py-2 text-white outline-none"/><button onClick={send} disabled={loading} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#e8b94e] text-black disabled:opacity-50"><Send className="h-5 w-5"/></button></div><div className="mt-2 text-center text-[10px] text-zinc-600">AI assistance is preliminary. Sargis confirms final repairability, price and appointment.</div></div></main></div>;
}
