import React from 'react';
import { Building2, Car, Clock3, Handshake, Tags, Truck, Phone, Camera, BadgeDollarSign, Wrench, CheckCircle2, Sparkles } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import MobileActionBar from '../components/MobileActionBar';
import { BRAND } from '../data/mock';

const benefits=[[Truck,'ON-SITE MOBILE SERVICE','We come to you'],[Tags,'VOLUME PRICING','Special rates for dealer accounts'],[Clock3,'FAST TURNAROUND','Get vehicles ready for sale faster'],[Handshake,'LONG-TERM PARTNERSHIPS','Reliable, professional, consistent service']];
const partners=[[Car,'DEALERSHIPS','New & pre-owned vehicle inventory'],[Wrench,'BODY SHOPS','Post-repair wheel restoration'],[Car,'USED CAR LOTS','Get vehicles sale-ready faster'],[Sparkles,'DETAIL SHOPS','Add value for your customers']];
const steps=[[Camera,'1','SEND PHOTOS','Send vehicle/wheel photos for a quick assessment.'],[BadgeDollarSign,'2','WE CONFIRM PRICING','Get clear business pricing before we arrive.'],[Truck,'3','WE COME TO YOUR LOT','Our mobile service comes directly to your location.'],[Wrench,'4','WHEELS REPAIRED ON-SITE','Professional cosmetic wheel repair at your location.'],[CheckCircle2,'5','VEHICLE READY FOR SALE','Get the vehicle back into your workflow faster.']];
const showcase=[['/LAMBO_!.jpg','LAMBORGHINI','Premium Wheel Repair'],['/Audi-1.JPG','AUDI','Cosmetic Wheel Repair'],['/Audi-2.JPG','AUDI','Wheel Finish Restoration']];

const Dealers=()=> <div className="min-h-screen bg-[#050607] pb-[68px] text-white md:pb-0"><Navbar/><main className="pt-[72px] md:pt-[82px]">
<section className="relative overflow-hidden border-b border-[#dcae45]/20"><div className="absolute inset-0"><img src="/LAMBO_!.jpg" alt="Premium wheel" className="h-full w-full object-cover object-right opacity-55"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/90 to-black/20"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-black/30"/></div><div className="relative mx-auto max-w-[1380px] px-5 py-16 md:px-8 md:py-24"><div className="max-w-[760px]"><div className="text-xs font-black uppercase tracking-[.25em] text-[#e8b94e]">Rim Repair Pro Business Program</div><h1 className="mt-4 font-display text-[46px] font-black uppercase leading-[.92] sm:text-[64px] lg:text-[78px]">Dealer & Body Shop<br/><span className="text-[#e8b94e]">Program</span></h1><p className="mt-5 max-w-[650px] text-lg font-semibold leading-8 text-zinc-200">Professional mobile wheel repair for dealerships, body shops, used car lots and detail shops.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#dealer-pricing" className="rounded-md bg-[#e8b94e] px-7 py-4 text-sm font-black text-black">REQUEST DEALER PRICING</a><a href={`tel:${BRAND.phoneTel}`} className="flex items-center gap-2 rounded-md border border-white/25 bg-black/40 px-7 py-4 text-sm font-black"><Phone className="h-4 w-4 text-[#e8b94e]"/>CALL {BRAND.phone}</a></div></div><div className="mt-14 grid max-w-[900px] gap-6 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([Icon,t,d])=><div key={t}><Icon className="h-8 w-8 text-[#e8b94e]"/><h2 className="mt-3 text-sm font-black leading-4">{t}</h2><p className="mt-2 text-sm text-zinc-300">{d}</p></div>)}</div></div></section>
<section className="border-b border-white/10 bg-[#08090a] py-14"><div className="mx-auto max-w-[1380px] px-5 md:px-8"><h2 className="text-center font-display text-4xl font-black uppercase">Who We <span className="text-[#e8b94e]">Work With</span></h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{partners.map(([Icon,t,d])=><article key={t} className="rounded-lg border border-white/10 bg-gradient-to-b from-[#17191b] to-[#0e1011] p-7 text-center"><Icon className="mx-auto h-9 w-9 text-[#e8b94e]"/><h3 className="mt-4 font-black">{t}</h3><p className="mt-2 text-sm text-zinc-300">{d}</p></article>)}</div></div></section>
<section className="border-b border-white/10 bg-[#050607] py-14 md:py-20"><div className="mx-auto max-w-[1380px] px-5 md:px-8"><h2 className="text-center font-display text-4xl font-black uppercase">How Dealer <span className="text-[#e8b94e]">Service Works</span></h2><div className="mt-10 grid gap-5 md:grid-cols-5">{steps.map(([Icon,n,t,d])=><article key={n} className="text-center"><div className="mx-auto grid h-8 w-8 place-items-center rounded-full bg-[#e8b94e] text-sm font-black text-black">{n}</div><Icon className="mx-auto mt-5 h-8 w-8 text-[#e8b94e]"/><h3 className="mt-4 text-sm font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{d}</p></article>)}</div></div></section>
<section className="bg-[#08090a] py-14 md:py-20"><div className="mx-auto max-w-[1380px] px-5 md:px-8"><h2 className="text-center font-display text-4xl font-black uppercase">Selected <span className="text-[#e8b94e]">Premium Work</span></h2><p className="mx-auto mt-3 max-w-xl text-center text-sm text-zinc-400">A few selected examples from Rim Repair Pro.</p><div className="mt-9 grid gap-5 md:grid-cols-3">{showcase.map(([src,name,service])=><figure key={src} className="overflow-hidden rounded-xl border border-white/10 bg-[#111315]"><div className="aspect-[4/3] overflow-hidden"><img src={src} alt={name} className="h-full w-full object-cover transition duration-500 hover:scale-105"/></div><figcaption className="p-5 text-center"><div className="font-black">{name}</div><div className="mt-1 text-sm text-[#e8b94e]">{service}</div></figcaption></figure>)}</div></div></section>
<section id="dealer-pricing" className="bg-[#050607] py-14 md:py-20"><div className="mx-auto max-w-[1180px] rounded-xl border border-[#e8b94e]/60 bg-gradient-to-br from-[#121416] to-[#08090a] p-6 md:p-10"><div className="grid gap-10 lg:grid-cols-2"><div><div className="font-display text-4xl font-black uppercase text-[#e8b94e]">Become a Partner</div><h2 className="mt-2 text-3xl font-black">Request Dealer Pricing</h2><p className="mt-5 max-w-lg leading-7 text-zinc-300">Send your business information and we'll follow up about dealer, recurring and volume pricing.</p><div className="mt-6 space-y-3 text-sm text-zinc-300">{['Mobile service at your location','Multiple wheels per visit','Business and recurring-account pricing'].map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="h-5 w-5 text-[#e8b94e]"/>{x}</div>)}</div></div><form onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=`Dealer / Body Shop Inquiry%0A%0ABusiness: ${encodeURIComponent(f.get('business'))}%0AContact: ${encodeURIComponent(f.get('contact'))}%0APhone: ${encodeURIComponent(f.get('phone'))}%0AZIP: ${encodeURIComponent(f.get('zip'))}%0AType: ${encodeURIComponent(f.get('type'))}%0AVolume: ${encodeURIComponent(f.get('volume'))}`;window.location.href=`sms:${BRAND.phoneTel}?&body=${msg}`;}}><div className="grid gap-3 sm:grid-cols-2"><input required name="business" placeholder="Business Name *" className="min-h-12 rounded border border-white/15 bg-white/[.05] px-4 text-sm outline-none focus:border-[#e8b94e]"/><input required name="contact" placeholder="Contact Name *" className="min-h-12 rounded border border-white/15 bg-white/[.05] px-4 text-sm outline-none focus:border-[#e8b94e]"/><input required name="phone" placeholder="Phone Number *" className="min-h-12 rounded border border-white/15 bg-white/[.05] px-4 text-sm outline-none focus:border-[#e8b94e]"/><input required name="zip" placeholder="ZIP Code *" className="min-h-12 rounded border border-white/15 bg-white/[.05] px-4 text-sm outline-none focus:border-[#e8b94e]"/><select name="type" className="min-h-12 rounded border border-white/15 bg-[#141618] px-4 text-sm"><option>Type of Business</option><option>Dealership</option><option>Body Shop</option><option>Used Car Lot</option><option>Detail Shop</option></select><select name="volume" className="min-h-12 rounded border border-white/15 bg-[#141618] px-4 text-sm"><option>Estimated Wheels Per Month</option><option>1–5</option><option>6–15</option><option>16–30</option><option>30+</option></select></div><button className="mt-3 w-full rounded bg-[#e8b94e] px-5 py-4 text-sm font-black text-black">TEXT MY INFORMATION</button></form></div></div></section>
</main><Footer/><MobileActionBar/></div>;
export default Dealers;
